name: Setup Android NDK r27c

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  download-ndk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create local NDK directory
        run: mkdir -p ndk

      - name: Setup Android NDK via Action
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          local-cache: true

      - name: Move NDK to repository folder
        run: |
          mv ${{ steps.setup-ndk.outputs.ndk-path }}/* ndk/

      - name: Verify NDK placement
        run: ls -la ndk
